services:
    Sidus\EAVModelBundle\Serializer\Denormalizer\EAVDataDenormalizer:
        parent: serializer.normalizer.object
        arguments:
            - '@Sidus\EAVModelBundle\Registry\FamilyRegistry'
            - '@sidus_eav_model.entity_manager'
            - '@Sidus\EAVModelBundle\Serializer\EntityProviderInterface'
            - '%sidus_eav_model.denormalizer.data.ignored_attributes%'
        tags:
            - { name: serializer.normalizer, priority: 9 }
