services:
    CleverAge\EAVManager\UserBundle\Event\AuthorableSubscriber:
        public: false
        autowire: true
        tags:
            - { name: doctrine.event_subscriber, connection: default }
