services:
    CleverAge\EAVManager\UserBundle\Form\Type\UserType:
        public: false
        autowire: true
        tags:
            - { name: form.type }

    CleverAge\EAVManager\UserBundle\Form\Type\GroupType:
        public: false
        tags:
            - { name: form.type }

    CleverAge\EAVManager\UserBundle\Form\Type\UserProfileType:
        public: false
        autowire: true
        tags:
            - { name: form.type }
