services:
    eavmanager_user.user.manager:
        alias: CleverAge\EAVManager\UserBundle\Domain\Manager\UserManagerInterface

    CleverAge\EAVManager\UserBundle\Domain\Manager\UserManagerInterface:
        alias: CleverAge\EAVManager\UserBundle\Infrastructure\Manager\UserManager

    CleverAge\EAVManager\UserBundle\Infrastructure\Manager\UserManager:
        arguments:
            - '@CleverAge\EAVManager\UserBundle\Security\UserProvider'
            - '@security.password_encoder'
            - '@doctrine'
            - '@validator'
            - '@CleverAge\EAVManager\UserBundle\Mailer\UserMailer'
            - '@logger'
