services:
    CleverAge\EAVManager\UserBundle\Domain\Manager\UserManagerInterface:
        class: CleverAge\EAVManager\UserBundle\Infrastructure\Manager\UserManager
        arguments:
            - '@CleverAge\EAVManager\UserBundle\Security\UserProvider'
            - '@Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface'
            - '@Doctrine\Common\Persistence\ManagerRegistry'
            - '@Symfony\Component\Validator\Validator\ValidatorInterface'
            - '@CleverAge\EAVManager\UserBundle\Mailer\UserMailer'
            - '@Psr\Log\LoggerInterface'
