parameters:
    eavmanager_user.normalizer.user.ignored_attributes:
        - password
        - plainPassword
        - salt
        - authenticationToken
        - rawRoles
        - combinedFamilyPermissions

services:
    CleverAge\EAVManager\UserBundle\Serializer\Normalizer\UserNormalizer:
        parent: serializer.normalizer.object
        arguments:
            - '@sidus_eav_model.serializer.handler.max_depth'
            - '@sidus_eav_model.serializer.handler.by_reference'
        calls:
            - [setIgnoredAttributes, ['%eavmanager_user.normalizer.user.ignored_attributes%']]
        tags:
            - { name: serializer.normalizer }

    eavmanager_user.normalizer.user.flat:
        class: Sidus\EAVModelBundle\Serializer\Normalizer\Flat\FlatNormalizer
        arguments:
            - '@CleverAge\EAVManager\UserBundle\Serializer\Normalizer\UserNormalizer'
            - [csv]
        tags:
            - { name: serializer.normalizer, priority: 1 }
