services:
    eavmanager_security.form.role_hierarchy.type:
        class: CleverAge\EAVManager\SecurityBundle\Form\Type\RoleHierarchyType
        arguments: ['@security.role_hierarchy']
        tags:
            - { name: form.type }

    eavmanager_security.form.family_permission.type:
        class: CleverAge\EAVManager\SecurityBundle\Form\Type\FamilyPermissionType
        arguments:
            - '@sidus_eav_model.family.registry'
        tags:
            - { name: form.type }
