services:
    CleverAge\EAVManager\SecurityBundle\Form\Type\RoleHierarchyType:
        public: false
        arguments:
            - '@security.role_hierarchy'
        tags:
            - { name: form.type }

    CleverAge\EAVManager\SecurityBundle\Form\Type\FamilyPermissionType:
        public: false
        autowire: true
        tags:
            - { name: form.type }
