services:
    CleverAge\EAVManager\SecurityBundle\Voter\FamilyVoter:
        public: false
        autowire: true
        tags:
            - { name: security.voter }

    CleverAge\EAVManager\SecurityBundle\Voter\EAVDataVoter:
        public: false
        autowire: true
        tags:
            - { name: security.voter }

    CleverAge\EAVManager\SecurityBundle\Voter\UserVoter:
        public: false
        autowire: true
        tags:
            - { name: security.voter }
