services:
    CleverAge\EAVManager\SecurityBundle\Voter\FamilyVoter:
        public: false
        arguments:
            - '@security.access.role_hierarchy_voter'
        tags:
            - { name: security.voter }

    CleverAge\EAVManager\SecurityBundle\Voter\EAVDataVoter:
        public: false
        autowire: true
        tags:
            - { name: security.voter }
