services:
    Sidus\EAVModelBundle\Serializer\Normalizer\EAVDataNormalizer:
        class: CleverAge\EAVManager\ApiPlatformBundle\Serializer\Normalizer\EAVDataNormalizer
        parent: serializer.normalizer.object
        public: false
        arguments:
            - '@Sidus\EAVModelBundle\Serializer\MaxDepthHandler'
            - '@Sidus\EAVModelBundle\Serializer\CircularReferenceHandler'
            - '@Sidus\EAVModelBundle\Serializer\ByReferenceHandler'
        calls:
            - [setIgnoredAttributes, ['%sidus_eav_model.normalizer.data.ignored_attributes%']]
            - [setReferenceAttributes, ['%sidus_eav_model.normalizer.data.reference_attributes%']]
            - [setIriConverter, ['@api_platform.iri_converter']]
        tags:
            - { name: serializer.normalizer }

    CleverAge\EAVManager\ApiPlatformBundle\Serializer\Normalizer\BaseApiNormalizer:
        parent: api_platform.serializer.normalizer.item
        public: false
        calls:
            - [setNormalizer, ['@Sidus\EAVModelBundle\Serializer\Normalizer\EAVDataNormalizer']]
        tags:
            - { name: serializer.normalizer, priority: 1 }

    # JsonLD Support
    CleverAge\EAVManager\ApiPlatformBundle\Serializer\Normalizer\JsonLdApiNormalizer:
        parent: api_platform.jsonld.normalizer.item
        public: false
        calls:
            - [setNormalizer, ['@Sidus\EAVModelBundle\Serializer\Normalizer\EAVDataNormalizer']]
        tags:
            - { name: serializer.normalizer, priority: 9 }
