services:
    CleverAge\EAVManager\ApiPlatformBundle\Serializer\Normalizer\BaseApiNormalizer:
        parent: api_platform.serializer.normalizer.item
        calls:
            - [setNormalizer, ['@CleverAge\EAVManager\UserBundle\Serializer\Normalizer\UserNormalizer']]
        tags:
            - { name: serializer.normalizer, priority: 1 }

    # JsonLD Support
    CleverAge\EAVManager\ApiPlatformBundle\Serializer\Normalizer\JsonLdApiNormalizer:
        parent: api_platform.jsonld.normalizer.item
        calls:
            - [setNormalizer, ['@CleverAge\EAVManager\UserBundle\Serializer\Normalizer\UserNormalizer']]
        tags:
            - { name: serializer.normalizer, priority: 9 }
