services:
    CleverAge\EAVManager\AssetBundle\Event\AssetSubscriber:
        public: false
        arguments:
            - '%sidus_eav_model.entity.data.class%'
        tags:
            - { name: doctrine.event_subscriber, connection: default }
