parameters:
    eavmanager.asset.family_map:
        Image: imageFile
        Document: documentFile

services:
    CleverAge\EAVManager\AssetBundle\Event\AssetSubscriber:
        public: false
        arguments:
            - '%eavmanager.asset.family_map%'
        tags:
            - { name: doctrine.event_subscriber, connection: default }
