services:
    CleverAge\EAVManager\AssetBundle\Serializer\Normalizer\ResourceNormalizer:
        parent: serializer.normalizer.object
        public: false
        arguments:
            - '@Sidus\FileUploadBundle\Manager\ResourceManagerInterface'
            -
                document: '@oneup_uploader.controller.document'
                image: '@oneup_uploader.controller.image'
            - '@Doctrine\Common\Persistence\ManagerRegistry'
            - '@Sidus\EAVModelBundle\Serializer\MaxDepthHandler'
            - '@Sidus\EAVModelBundle\Serializer\ByReferenceHandler'
        tags:
            - { name: serializer.normalizer }
