services:
    CleverAge\EAVManager\ApiPlatformBundle\EAV\Filter\AbstractEAVFilter:
        abstract: true
        arguments:
            - '@request_stack'
            - '@Sidus\EAVModelBundle\Registry\FamilyRegistry'
            - '@CleverAge\EAVManager\EAVModelBundle\Resolver\FamilyResolver'
            - '@Sidus\EAVFilterBundle\Filter\EAVFilterHelper'

    CleverAge\EAVManager\ApiPlatformBundle\EAV\Filter\SearchFilter:
        parent: CleverAge\EAVManager\ApiPlatformBundle\EAV\Filter\AbstractEAVFilter
        abstract: true
        arguments:
            - [string]

    CleverAge\EAVManager\ApiPlatformBundle\EAV\Filter\BooleanFilter:
        parent: CleverAge\EAVManager\ApiPlatformBundle\EAV\Filter\AbstractEAVFilter
        abstract: true
        arguments:
            - [bool]

    CleverAge\EAVManager\ApiPlatformBundle\EAV\Filter\DateFilter:
        parent: CleverAge\EAVManager\ApiPlatformBundle\EAV\Filter\AbstractEAVFilter
        abstract: true
        arguments:
            - [DateTimeInterface]

    CleverAge\EAVManager\ApiPlatformBundle\EAV\Filter\NumericFilter:
        parent: CleverAge\EAVManager\ApiPlatformBundle\EAV\Filter\AbstractEAVFilter
        abstract: true
        arguments:
            - [float]

    CleverAge\EAVManager\ApiPlatformBundle\EAV\Filter\OrderFilter:
        parent: CleverAge\EAVManager\ApiPlatformBundle\EAV\Filter\AbstractEAVFilter
        abstract: true
        arguments:
            - [int, bool, DateTimeInterface, float, string]

    CleverAge\EAVManager\ApiPlatformBundle\EAV\Filter\RangeFilter:
        parent: CleverAge\EAVManager\ApiPlatformBundle\EAV\Filter\AbstractEAVFilter
        abstract: true
        arguments:
            - [int, DateTimeInterface, float]

    # Overriding stuff because FUCK YOU
    api_platform.doctrine.orm.query_extension.filter_eager_loading:
        abstract: true
