services:
    CleverAge\EAVManager\ApiPlatformBundle\EAV\Filter\AbstractEAVFilter:
        abstract: true
        autowire: true

    CleverAge\EAVManager\ApiPlatformBundle\EAV\Filter\SearchFilter:
        parent: eavmanager_api_platform.filter.abstract_eav
        abstract: true
        arguments:
            - [string]

    CleverAge\EAVManager\ApiPlatformBundle\EAV\Filter\BooleanFilter:
        parent: eavmanager_api_platform.filter.abstract_eav
        abstract: true
        arguments:
            - [bool]

    CleverAge\EAVManager\ApiPlatformBundle\EAV\Filter\DateFilter:
        parent: eavmanager_api_platform.filter.abstract_eav
        abstract: true
        arguments:
            - [DateTimeInterface]

    CleverAge\EAVManager\ApiPlatformBundle\EAV\Filter\NumericFilter:
        parent: eavmanager_api_platform.filter.abstract_eav
        abstract: true
        arguments:
            - [float]

    CleverAge\EAVManager\ApiPlatformBundle\EAV\Filter\OrderFilter:
        parent: eavmanager_api_platform.filter.abstract_eav
        abstract: true
        arguments:
            - [int, bool, DateTimeInterface, float, string]

    CleverAge\EAVManager\ApiPlatformBundle\EAV\Filter\RangeFilter:
        parent: eavmanager_api_platform.filter.abstract_eav
        abstract: true
        arguments:
            - [int, DateTimeInterface, float]

    # Overriding stuff because FUCK YOU
    api_platform.doctrine.orm.query_extension.filter_eager_loading:
        abstract: true
