services:
    eavmanager_process.task.eav_reader:
        alias: CleverAge\EAVManager\ProcessBundle\Task\EAVReaderTask

    eavmanager_process.task.eav_criteria_reader:
        alias: CleverAge\EAVManager\ProcessBundle\Task\EAVCriteriaReaderTask

    eav_manager_process.transformer.unique_eav_finder:
        alias: CleverAge\EAVManager\ProcessBundle\Transformer\UniqueEAVFinderTransformer

    eav_manager_process.transformer.single_eav_finder:
        alias: CleverAge\EAVManager\ProcessBundle\Transformer\SingleEAVFinderTransformer

    eav_manager_process.transformer.resource_to_asset:
        alias: CleverAge\EAVManager\ProcessBundle\Transformer\ResourceToAssetTransformer
