services:
    CleverAge\EAVManager\ProcessBundle\Task\EAVReaderTask:
        shared: false
        autowire: true

    CleverAge\EAVManager\ProcessBundle\Task\EAVCriteriaReaderTask:
        shared: false
        autowire: true
