services:
    CleverAge\EAVManager\ProcessBundle\Task\EAVReaderTask:
        shared: false
        arguments:
            - '@sidus_eav_model.entity_manager'
            - '@Sidus\EAVModelBundle\Registry\FamilyRegistry'
            - '@Sidus\EAVModelBundle\Doctrine\EAVFinder'

    CleverAge\EAVManager\ProcessBundle\Task\EAVCriteriaReaderTask:
        parent: CleverAge\EAVManager\ProcessBundle\Task\EAVReaderTask
        shared: false
