services:
    CleverAge\EAVManager\ProcessBundle\Transformer\:
        resource: '../../../Transformer/*'
        autowire: true
        public: true
        tags:
            - { name: cleverage.transformer }
