services:
    CleverAge\EAVManager\ProcessBundle\Transformer\UniqueEAVFinderTransformer:
        autowire: true
        tags:
            - { name: cleverage.transformer }

    CleverAge\EAVManager\ProcessBundle\Transformer\SingleEAVFinderTransformer:
        autowire: true
        tags:
            - { name: cleverage.transformer }

    CleverAge\EAVManager\ProcessBundle\Transformer\ResourceToAssetTransformer:
        autowire: true
        tags:
            - { name: cleverage.transformer }
