services:
    CleverAge\EAVManager\AdminBundle\Listener\Routing\CacheListener:
        autowire: true
        public: false
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }
