services:
    CleverAge\EAVManager\AdminBundle\Form\AdminFormHelper:
        public: false
        autowire: true

    CleverAge\EAVManager\AdminBundle\Form\EAVFormHelper:
        public: false
        autowire: true

    CleverAge\EAVManager\AdminBundle\Templating\AdminTemplatingHelper:
        public: false
        autowire: true

    CleverAge\EAVManager\AdminBundle\Templating\EAVTemplatingHelper:
        public: false
        autowire: true

    CleverAge\EAVManager\AdminBundle\DataGrid\DataGridHelper:
        public: false
        autowire: true

    CleverAge\EAVManager\AdminBundle\DataGrid\EAVDataGridHelper:
        public: false
        autowire: true
