sidus_admin:
    configurations:
        group:
            entity: CleverAge\EAVManager\UserBundle\Entity\Group
            controller_pattern:
                - CleverAge\EAVManager\AdminBundle\Action\{{Action}}Action
            template_pattern:
                - CleverAgeEAVManagerAdminBundle:Base:{{action}}.html.twig
            form_type: CleverAge\EAVManager\UserBundle\Form\Type\GroupType
            prefix: /groups
            actions:
                list:
                    path: /
                create:
                    path: /create
                read:
                    path: /read/{id}
                edit:
                    path: /edit/{id}
                delete:
                    path: /delete/{id}
            options:
                hidden: true
