sidus_admin:
    configurations:
        media_browser:
            controller: CleverAgeEAVManagerAdminBundle:EAVData # Absolute reference in case it's overriden in the app
            entity: '%sidus_data_class%'
            prefix: /medias_browser
            actions:
                list:
                    path:     /{familyCode}/list
                create:
                    path:     /{familyCode}/create
                    form_type: '%eav_form.type%'
                read:
                    path:     /{familyCode}/read/{id}
                    form_type: '%eav_form.type%'
                edit:
                    path:     /{familyCode}/edit/{id}
                    form_type: '%eav_form.type%'
                    template: '@CleverAgeEAVManagerAdmin/Asset/edit.html.twig'
                delete:
                    path:     /{familyCode}/delete/{id}
            options:
                hidden: true
                allow_back: true
                families:
                    Image:
                        datagrid: image_browser
                    Document:
                        datagrid: document_browser
