sidus_admin:
    configurations:
        resource:
            entity: CleverAge\EAVManager\AssetBundle\Entity\Document
            controller_pattern:
                - 'CleverAge\EAVManager\AdminBundle\Action\{{Action}}Action'
            template_pattern:
                - '@CleverAgeEAVManagerAdmin/Base/{{action}}.{{format}}.twig'
            prefix: /resources
            actions:
                list:
                    path: /
                delete:
                    path: /{id}/delete
            options:
                hidden: true
