sidus_admin:
    configurations:
        user:
            entity: CleverAge\EAVManager\UserBundle\Entity\User
            controller_pattern:
                - CleverAge\EAVManager\AdminBundle\Action\User\{{Action}}Action
                - CleverAge\EAVManager\AdminBundle\Action\{{Action}}Action
            template_pattern:
                - CleverAgeEAVManagerAdminBundle:User:{{action}}.html.twig
                - CleverAgeEAVManagerAdminBundle:Base:{{action}}.html.twig
            form_type: CleverAge\EAVManager\UserBundle\Form\Type\UserType
            prefix: /users
            actions:
                list:
                    path:     /
                create:
                    path:     /create
                read:
                    path:     /read/{id}
                edit:
                    path:     /edit/{id}
                delete:
                    path:     /delete/{id}
                resetPassword:
                    path:     /reset-password/{id}
            options:
                hidden: true
