sidus_data_grid:
    configurations:
        user:
            query_handler:
                provider: doctrine
                options:
                    entity: CleverAgeEAVManagerUserBundle:User
                sortable:
                    - id
                    - createdAt
                    - username
                    - email
                filters:
                    createdAt:
                        type: date_range
                        label: Création
                    email: ~
                    username: ~
            columns:
                id:
                    label: '#'
                username:
                    template: '%clickable.template%'
                email:
                    template: '%clickable.template%'
                lastName:
                    property_path: data.lastName
                firstName:
                    property_path: data.firstName
                printableRoles: ~
                createdAt: ~
                actions:
                    template: '@CleverAgeEAVManagerAdmin/User/partials/list.row.actions.html.twig'
            actions:
                create: '%create.button%'
