CleverAge\EAVManager\UserBundle\Entity\User:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: 
             fields: username
             errorPath: username
             message: admin.user.form.username.already_used
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
             fields: email
             errorPath: email
             message: admin.user.form.email.already_used
    properties:
        username:
            - NotBlank:
                message: admin.user.form.username.blank
            - Length:
                min: 2
                minMessage: admin.user.form.username.short
                max: 255
                maxMessage: admin.user.form.username.long
        email:
            - NotBlank:
                message: admin.user.form.email.blank
            - Length:
                min: 2
                minMessage: admin.user.form.email.short
                max: 255
                maxMessage: admin.user.form.email.long
            - Email:
                message: admin.user.form.email.invalid
        plainPassword:
            - NotBlank:
                message: admin.user.form.password.blank
                groups: [ 'Registration', 'ResetPassword', 'ChangePassword' ]
            - Length:
                min: 6
                minMessage: admin.user.form.password.short
                groups: [ 'Registration', 'ResetPassword', 'ChangePassword']
        familyPermissions:
            - Valid: ~

CleverAge\EAVManager\UserBundle\Entity\Group:
    properties:
        name:
            - NotBlank:
                message: admin.group.form.name.blank
            - Length:
                min: 2
                minMessage: admin.group.form.name.short
                max: 255
                maxMessage: admin.group.form.name.long
